steps:
  - name: gcr.io/cloud-builders/wget
    args:
      - '-O'
      - 'sops'
      - 'https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64'
  - name: gcr.io/cloud-builders/wget
    args:
      - '-O'
      - 'yq'
      - 'https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64'
  - name: gcr.io/cloud-builders/wget
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        chmod +x sops yq;
        ./sops -d --input-type yaml --output-type yaml configuration/env/dev-poc/kvms.yaml.enc| ./yq -o json | sed '1d'  | sed -e '$d' | sed -e 's/"data"://1' > configuration/env/dev-poc/kvms.json
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - |
        echo -n $$APIGEE_CD_KEY > key.json
    entrypoint: /bin/bash
    secretEnv:
      - APIGEE_CD_KEY
  - name: 'maven:3.3-jdk-8'
    args:
      - clean
      - install
      - '-Dfile=../key.json'
      - '-Pdev-poc'
      - '-Dapigee.config.dir=.'
      - '-Dapigee.config.options=update'
    dir: configuration
    entrypoint: mvn
logsBucket: 'gs://apigeex-deploy-trigger'
options:
  logging: GCS_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/1012847900619/secrets/apigee-cicd-test-key/versions/latest
      env: APIGEE_CD_KEY