steps:
  - name: gcr.io/cloud-builders/wget
    args:
      - '-O'
      - 'sops'
      - 'https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64'
  - name: gcr.io/cloud-builders/wget
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        chmod +x sops;
        sops -d --output configuration/env/dev-poc/kvms.json configuration/env/dev-poc/kvms.json.enc;
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - |
        echo -n $$APIGEE_CD_KEY > key.json
    entrypoint: /bin/bash
    secretEnv:
      - APIGEE_CD_KEY
  - name: 'maven:3.3-jdk-8'
    args:
      - clean
      - install
      - '-Dfile=../key.json'
      - '-Pdev-poc'
      - '-Dapigee.config.dir=.'
      - '-Dapigee.config.options=update'
    dir: configuration
    entrypoint: mvn
availableSecrets:
  secretManager:
    - versionName: projects/1012847900619/secrets/apigee-cicd-test-key/versions/latest
      env: APIGEE_CD_KEY