creation_rules:
  - path_regex: kvms.json.enc$
    gcp_kms: projects/apigee-x-poc-374912/locations/europe-west1/keyRings/key-ring-apigee-x/cryptoKeys/crypto-key-apigee
    encrypted_suffix: secretTemplates